---
version: "2"
run:
  concurrency: 4
  go: "1.25"
  timeout: 10m

linters:
  enable:
    - gocritic
    - gosec
    - nlreturn
    - revive
    - errcheck
    - copyloopvar
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
    - embeddedstructfieldcheck
    - ginkgolinter
    - importas
    - nilerr
    - whitespace

  settings:
    embeddedstructfieldcheck:
      # Checks that sync.Mutex and sync.RWMutex are not used as embedded fields
      forbid-mutex: true
    importas:
      alias:
        # Kubernetes core packages
        - pkg: k8s.io/api/(\w+)/(v[\w\d]+)
          alias: $1$2
        - pkg: k8s.io/apimachinery/pkg/apis/(\w+)/(v[\w\d]+)
          alias: $1$2
        - pkg: k8s.io/apimachinery/pkg/api/([^m]\w+)
          alias: api${1}
        - pkg: k8s.io/apimachinery/pkg/util/(\w+)
          alias: util${1}
        - pkg: k8s.io/client-go/kubernetes
          alias: kubernetesclientset
        - pkg: k8s.io/client-go/tools/cache
          alias: toolscache
        # Controller-runtime packages
        - pkg: sigs.k8s.io/controller-runtime/pkg/client/fake
          alias: fakeclient
        - pkg: sigs.k8s.io/controller-runtime/pkg/log/zap
          alias: logzap
        - pkg: sigs.k8s.io/controller-runtime/pkg/log
          alias: logf
        # Testing packages
        - pkg: go.uber.org/mock/gomock
          alias: gmock
    misspell:
      mode: restricted
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: dot-imports
          disabled: true
        - name: function-length
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: package-comments
          disabled: true
        - name: use-errors-new
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: comment-spacings
          disabled: true
        - name: unused-parameter
          disabled: true
        - name: unused-receiver
          disabled: true
        - name: enforce-switch-style
          disabled: true
        - name: var-naming
          arguments:
            - []
            - []
            - - skip-package-name-checks: true
        - name: unhandled-error
          disabled: false
          exclude: [""]
          arguments:
            - fmt.Print
            - fmt.Printf
            - fmt.Println
            - fmt.Fprint
            - fmt.Fprintf
            - fmt.Fprintln
        - name: duplicated-imports
        - name: unreachable-code
        - name: context-as-argument
        - name: early-return
        - name: exported
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # errcheck: Most programs ignore errors on these functions and it's usually ok
    - path: (.+)\.go$
      text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
      linters:
        - errcheck
    # revive: Allow certain common patterns
    - path: (.+)\.go$
      text: var-naming # ((var|const|struct field|func) .* should be .*
      linters:
        - revive
    - path: (.+)\.go$
      text: package-comments # package comment should be of the form
      linters:
        - revive
    - path: (.+)\.go$
      text: 'exported: (type|func) name will be used as .* by other packages, and that stutters;'
      linters:
        - revive
    # staticcheck: Allow deprecated usage in some cases
    - linters:
        - staticcheck
      text: 'SA1019:' # Excludes messages where deprecated variables are used

formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
    gofmt:
      rewrite-rules:
        - pattern: interface{}
          replacement: any
