apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: pvc-autoscaler
build:
  artifacts:
    - image: local-skaffold/pvc-autoscaler
      ko:
        dependencies:
          paths:
            - api/autoscaling/v1alpha1
            - cmd/pvc-autoscaler
            - internal/common
            - internal/controller/autoscaling
            - internal/metrics
            - internal/metrics/source
            - internal/metrics/source/prometheus
            - internal/periodic
            - internal/utils
            - VERSION
        main: ./cmd/pvc-autoscaler
manifests:
  kustomize:
    paths:
      - config/default
deploy:
  helm:
    releases:
      - name: cert-manager
        repo: https://charts.jetstack.io
        remoteChart: cert-manager
        version: v1.16.1
        namespace: cert-manager
        createNamespace: true
        setValues:
          crds.enabled: "true"
      - name: kind-prometheus
        repo: https://prometheus-community.github.io/helm-charts
        remoteChart: kube-prometheus-stack
        namespace: monitoring
        createNamespace: true
  kubectl:
    flags:
      apply:
        - --server-side
        - --force-conflicts
