# permissions for end users to view persistentvolumeclaimautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pvc-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: autoscaling-persistentvolumeclaimautoscaler-viewer-role
rules:
- apiGroups:
  - autoscaling.gardener.cloud
  resources:
  - persistentvolumeclaimautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling.gardener.cloud
  resources:
  - persistentvolumeclaimautoscalers/status
  verbs:
  - get
