#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

_SCRIPT_DIR=$( dirname `readlink -f -- "${0}"` )
_REPO_ROOT="${_SCRIPT_DIR}/.."

echo "${EFFECTIVE_VERSION}" > "${_REPO_ROOT}/VERSION"
