#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

_SCRIPT_DIR=$( dirname `readlink -f -- "${0}"` )
_REPO_ROOT="${_SCRIPT_DIR}/.."

git config --global user.email 'gardener@sap.com'
git config --global user.name 'Gardener CI/CD'

make -C "${_REPO_ROOT}" lint test
