//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentVolumeClaimAutoscaler) DeepCopyInto(out *PersistentVolumeClaimAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentVolumeClaimAutoscaler.
func (in *PersistentVolumeClaimAutoscaler) DeepCopy() *PersistentVolumeClaimAutoscaler {
	if in == nil {
		return nil
	}
	out := new(PersistentVolumeClaimAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PersistentVolumeClaimAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentVolumeClaimAutoscalerList) DeepCopyInto(out *PersistentVolumeClaimAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PersistentVolumeClaimAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentVolumeClaimAutoscalerList.
func (in *PersistentVolumeClaimAutoscalerList) DeepCopy() *PersistentVolumeClaimAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(PersistentVolumeClaimAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PersistentVolumeClaimAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentVolumeClaimAutoscalerSpec) DeepCopyInto(out *PersistentVolumeClaimAutoscalerSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	if in.VolumePolicies != nil {
		in, out := &in.VolumePolicies, &out.VolumePolicies
		*out = make([]VolumePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentVolumeClaimAutoscalerSpec.
func (in *PersistentVolumeClaimAutoscalerSpec) DeepCopy() *PersistentVolumeClaimAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(PersistentVolumeClaimAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentVolumeClaimAutoscalerStatus) DeepCopyInto(out *PersistentVolumeClaimAutoscalerStatus) {
	*out = *in
	in.LastCheck.DeepCopyInto(&out.LastCheck)
	in.NextCheck.DeepCopyInto(&out.NextCheck)
	if in.PersistentVolumeClaims != nil {
		in, out := &in.PersistentVolumeClaims, &out.PersistentVolumeClaims
		*out = make([]PersistentVolumeClaimStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentVolumeClaimAutoscalerStatus.
func (in *PersistentVolumeClaimAutoscalerStatus) DeepCopy() *PersistentVolumeClaimAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(PersistentVolumeClaimAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentVolumeClaimStatus) DeepCopyInto(out *PersistentVolumeClaimStatus) {
	*out = *in
	if in.UsedSpacePercent != nil {
		in, out := &in.UsedSpacePercent, &out.UsedSpacePercent
		*out = new(int)
		**out = **in
	}
	if in.UsedInodesPercent != nil {
		in, out := &in.UsedInodesPercent, &out.UsedInodesPercent
		*out = new(int)
		**out = **in
	}
	if in.CurrentSize != nil {
		in, out := &in.CurrentSize, &out.CurrentSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.TargetSize != nil {
		in, out := &in.TargetSize, &out.TargetSize
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentVolumeClaimStatus.
func (in *PersistentVolumeClaimStatus) DeepCopy() *PersistentVolumeClaimStatus {
	if in == nil {
		return nil
	}
	out := new(PersistentVolumeClaimStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingRules) DeepCopyInto(out *ScalingRules) {
	*out = *in
	if in.UtilizationThresholdPercent != nil {
		in, out := &in.UtilizationThresholdPercent, &out.UtilizationThresholdPercent
		*out = new(int)
		**out = **in
	}
	if in.StepPercent != nil {
		in, out := &in.StepPercent, &out.StepPercent
		*out = new(int)
		**out = **in
	}
	if in.MinStepAbsolute != nil {
		in, out := &in.MinStepAbsolute, &out.MinStepAbsolute
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.CooldownDuration != nil {
		in, out := &in.CooldownDuration, &out.CooldownDuration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingRules.
func (in *ScalingRules) DeepCopy() *ScalingRules {
	if in == nil {
		return nil
	}
	out := new(ScalingRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumePolicy) DeepCopyInto(out *VolumePolicy) {
	*out = *in
	out.MaxCapacity = in.MaxCapacity.DeepCopy()
	if in.ScaleUp != nil {
		in, out := &in.ScaleUp, &out.ScaleUp
		*out = new(ScalingRules)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumePolicy.
func (in *VolumePolicy) DeepCopy() *VolumePolicy {
	if in == nil {
		return nil
	}
	out := new(VolumePolicy)
	in.DeepCopyInto(out)
	return out
}
