apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
# Protect the /metrics endpoint by putting it behind auth.
- path: manager_auth_proxy_patch.yaml
- path: manager_config_patch.yaml